export const RECIPES_LOADING = "RECIPES_LOADING";
export const RECIPES_FAILED = "RECIPES_FAILED";
export const RECIPES_SUCCESS = "RECIPES_SUCCESS";

export const RECIPE_LOADING = "RECIPE_LOADING";
export const RECIPE_FAILED = "RECIPE_FAILED";
export const RECIPE_SUCCESS = "RECIPE_SUCCESS";
